# Generated by Django 5.2.4 on 2025-09-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='describtion',
            new_name='description',
        ),
    ]
