# Generated by Django 6.0.2 on 2026-05-05 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0003_mpesaidempotencyrecord_paymentprovider_platformfee_and_more'),
        ('saccomembership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('category', models.CharField(choices=[('SAVING_DEPOSIT', 'Saving deposit'), ('SAVING_WITHDRAWAL', 'Saving withdrawal'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('LOAN_REPAYMENT', 'Loan repayment'), ('FEE', 'Fee'), ('PENALTY', 'Penalty'), ('DIVIDEND', 'Dividend'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saccomembership.membership')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['membership', 'created_at'], name='ledger_ledg_members_20ae27_idx')],
            },
        ),
    ]
