# Generated by Django 5.1.1 on 2026-06-24 11:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('category', models.CharField(choices=[('SAVING_DEPOSIT', 'Saving deposit'), ('SAVING_WITHDRAWAL', 'Saving withdrawal'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('LOAN_REPAYMENT', 'Loan repayment'), ('FEE', 'Fee'), ('PENALTY', 'Penalty'), ('DIVIDEND', 'Dividend'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
