# Generated by Django 5.1.1 on 2026-06-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('payments', '0001_initial'),
        ('saccomembership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saccomembership.membership'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['membership', 'created_at'], name='ledger_ledg_members_20ae27_idx'),
        ),
    ]
