# Generated by Django 6.0.2 on 2026-07-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='category',
            field=models.CharField(choices=[('SAVING_DEPOSIT', 'Saving deposit'), ('SAVING_WITHDRAWAL', 'Saving withdrawal'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('LOAN_REPAYMENT', 'Loan repayment'), ('FEE', 'Fee'), ('PENALTY', 'Penalty'), ('DIVIDEND', 'Dividend'), ('DIVIDEND_PAYOUT', 'Dividend payout'), ('ADJUSTMENT', 'Adjustment')], max_length=30),
        ),
    ]
