# Generated by Django 5.2.3 on 2026-01-29 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rename_website_sacco_website_url_sacco_is_internal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('left', 'Left Sacco')], default='pending', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saccomembership', to='accounts.sacco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sacco')},
            },
        ),
        migrations.CreateModel(
            name='SaccoField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.SlugField(help_text='Internal key e.g. national_id', max_length=100)),
                ('field_label', models.CharField(help_text='Displayed label e.g. National ID Number', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('file', 'File Upload')], default='text', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='accounts.sacco')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('sacco', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='MembershipFieldData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_data', to='saccomembership.membership')),
                ('sacco_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saccomembership.saccofield')),
            ],
            options={
                'unique_together': {('membership', 'sacco_field')},
            },
        ),
    ]
