# Generated by Django 5.2.3 on 2025-11-03 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_website_sacco_website_url_sacco_is_internal'),
        ('saccomembership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saccofield',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('file', 'File Upload')], default='text', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='accounts.sacco')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipFieldData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_data', to='saccomembership.membership')),
                ('sacco_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saccomembership.saccofield')),
            ],
        ),
    ]
