# Generated by Django 5.2.3 on 2026-01-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_website_sacco_website_url_sacco_is_internal'),
        ('saccomembership', '0002_saccofield_membershipfielddata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saccofield',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='saccofield',
            unique_together={('sacco', 'field_key')},
        ),
        migrations.AddField(
            model_name='saccofield',
            name='field_key',
            field=models.SlugField(default='default_key', help_text='Internal key e.g. national_id', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saccofield',
            name='field_label',
            field=models.CharField(default='default_key', help_text='Displayed label e.g. National ID Number', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saccofield',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='membershipfielddata',
            unique_together={('membership', 'sacco_field')},
        ),
        migrations.RemoveField(
            model_name='saccofield',
            name='field_name',
        ),
    ]
