# Generated by Django 5.2.3 on 2025-11-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sacco',
            old_name='website',
            new_name='website_url',
        ),
        migrations.AddField(
            model_name='sacco',
            name='is_internal',
            field=models.BooleanField(default=True),
        ),
    ]
