# Generated by Django 6.0.2 on 2026-05-05 13:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
        ('payments', '0003_mpesaidempotencyrecord_paymentprovider_platformfee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revenue_type', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('TRANSACTION_FEE', 'Transaction fee'), ('OTHER', 'Other')], default='SUBSCRIPTION', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('sacco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sacco')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SaccoSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sacco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.sacco')),
            ],
            options={
                'ordering': ['sacco__name'],
            },
        ),
    ]
