# Generated by Django 6.0.4 on 2026-05-13 14:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_kyc_document_storage_and_huduma'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySaccoInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='GENERATED', max_length=20)),
                ('report_payload', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_invoices', to='accounts.sacco')),
            ],
            options={
                'ordering': ['-period_end', 'sacco__name'],
                'unique_together': {('sacco', 'period_start', 'period_end')},
            },
        ),
    ]
