# Generated by Django 5.1.1 on 2026-06-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('billing', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformrevenue',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='saccosubscription',
            name='sacco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.sacco'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlysaccoinvoice',
            unique_together={('sacco', 'period_start', 'period_end')},
        ),
    ]
