# Generated by Django 6.0.2 on 2026-08-13 07:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_kycverification_iprs_attempted_at_and_more'),
        ('billing', '0003_platformrevenue_is_collected'),
        ('payments', '0004_transaction_status_sent_amount_mismatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('billing_month', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_items_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('suspended', 'SACCO Suspended')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.sacco')),
            ],
            options={
                'db_table': 'billing_invoices',
                'ordering': ['-billing_month'],
                'unique_together': {('sacco', 'billing_month')},
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('internal', 'Internal')], max_length=20)),
                ('payment_ref', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.invoice')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Member Deposit'), ('repayment', 'Loan Repayment'), ('disbursement', 'Loan Disbursement'), ('withdrawal', 'Savings Withdrawal')], max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_model', models.CharField(max_length=30)),
                ('rate_applied', models.CharField(max_length=80)),
                ('tier_applied', models.CharField(blank=True, max_length=120, null=True)),
                ('billing_month', models.DateField()),
                ('invoiced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.invoice')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.sacco')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.transaction')),
            ],
            options={
                'db_table': 'billing_invoice_line_items',
                'indexes': [models.Index(fields=['sacco', 'billing_month', 'invoiced'], name='billing_inv_sacco_i_5ef9c7_idx'), models.Index(fields=['transaction_type', 'billing_month'], name='billing_inv_transac_de1d19_idx')],
            },
        ),
    ]
