# Generated by Django 6.0.2 on 2026-09-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_invoicepayment_invoicelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='suspension_warning_sent_at',
            field=models.DateTimeField(blank=True, help_text="Set once billing.tasks.send_billing_suspension_warnings notifies this invoice's SACCO that suspension is approaching, so the daily sweep does not re-notify for the same invoice every day it stays overdue.", null=True),
        ),
    ]
