# Generated by Django 5.0.6 on 2026-05-06 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
        ('saccomanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('MEMBER', 'Member'), ('SACCO_ADMIN', 'Sacco Admin'), ('SUPER_ADMIN', 'Super Admin')], help_text='The role name (MEMBER, SACCO_ADMIN, SUPER_ADMIN).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sacco', models.ForeignKey(blank=True, help_text='The SACCO this role is scoped to. Null for platform-wide roles.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_roles', to='accounts.sacco')),
                ('user', models.ForeignKey(help_text='The user who holds this role.', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'sacco', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.CharField(help_text='Resource name (e.g., loans, members, reports).', max_length=50)),
                ('can_create', models.BooleanField(default=False, help_text='Allow creation of this resource.')),
                ('can_read', models.BooleanField(default=True, help_text='Allow reading this resource.')),
                ('can_update', models.BooleanField(default=False, help_text='Allow updating this resource.')),
                ('can_delete', models.BooleanField(default=False, help_text='Allow deletion of this resource.')),
                ('role', models.ForeignKey(help_text='The role this permission belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='saccomanagement.role')),
            ],
            options={
                'unique_together': {('role', 'resource')},
            },
        ),
    ]
