# Generated by Django 6.0.2 on 2026-07-15 07:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_saccosettings_sms_daily_limit'),
        ('saccomanagement', '0003_complianceflag'),
        ('saccomembership', '0002_membershipdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'message',
                    models.TextField(
                        validators=[
                            django.core.validators.MaxLengthValidator(918),
                        ],
                    ),
                ),
                ('audience_filter', models.JSONField(default=dict)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('DRAFT', 'Draft'),
                            ('QUEUED', 'Queued'),
                            ('SENDING', 'Sending'),
                            ('COMPLETED', 'Completed'),
                            ('FAILED', 'Failed'),
                        ],
                        default='DRAFT',
                        max_length=20,
                    ),
                ),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_sms_campaigns',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'sacco',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sms_campaigns',
                        to='accounts.sacco',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSCampaignRecipient',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('phone_number', models.CharField(max_length=20)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('SENT', 'Sent'),
                            ('FAILED', 'Failed'),
                        ],
                        default='PENDING',
                        max_length=20,
                    ),
                ),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                (
                    'error_message',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    'campaign',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='recipients',
                        to='saccomanagement.smscampaign',
                    ),
                ),
                (
                    'membership',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sms_campaign_recipients',
                        to='saccomembership.membership',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('campaign', 'membership')},
            },
        ),
    ]
