# Generated by Django 6.0.2 on 2026-08-28 13:57
#
# This migration adds immutable snapshot fields to DataConsentLog for audit trail
# preservation after user deletion, and changes FK delete behavior from CASCADE
# to SET_NULL to preserve compliance records.
#
# Duplicate check: No duplicate (user, consent_type, version) rows found in UserConsent
# prior to adding the unique constraint. The constraint can be applied cleanly.
#
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_snapshot_fields(apps, schema_editor):
    """Populate snapshot fields for existing DataConsentLog records."""
    DataConsentLog = apps.get_model('saccomanagement', 'DataConsentLog')

    for log in DataConsentLog.objects.all():
        if log.user:
            log.user_reference = f"{log.user.id}:{log.user.email}"
        if log.accessed_by:
            log.accessed_by_reference = f"{log.accessed_by.id}:{log.accessed_by.email}"
        log.save(update_fields=['user_reference', 'accessed_by_reference'])


def reverse_populate_snapshot_fields(apps, schema_editor):
    """Reverse operation - clear snapshot fields."""
    DataConsentLog = apps.get_model('saccomanagement', 'DataConsentLog')
    DataConsentLog.objects.all().update(
        user_reference=None,
        accessed_by_reference=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('saccomanagement', '0004_smscampaign_smscampaignrecipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconsentlog',
            name='accessed_by_reference',
            field=models.CharField(blank=True, editable=False, help_text='Immutable snapshot: accessed_by ID and email at time of logging.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataconsentlog',
            name='user_reference',
            field=models.CharField(blank=True, editable=False, help_text='Immutable snapshot: user ID and email at time of logging.', max_length=255, null=True),
        ),
        migrations.RunPython(
            populate_snapshot_fields,
            reverse_populate_snapshot_fields,
        ),
        migrations.AlterField(
            model_name='dataconsentlog',
            name='accessed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataconsentlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_consent_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
