# Generated by Django 6.0.2 on 2026-09-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccomanagement', '0005_dataconsentlog_accessed_by_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberimportjob',
            name='protected_details',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='memberimportjob',
            name='protected_rows',
            field=models.PositiveIntegerField(default=0, help_text='Rows for an existing member whose current status (SUSPENDED, LEFT, UNDER_REVIEW, REJECTED) was deliberately left unchanged by this import, rather than being overwritten to APPROVED.'),
        ),
    ]
