# Generated by Django 6.0.2 on 2026-09-08 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_saccopaymentconfig_manage_payment_secrets_permission'),
        ('saccomanagement', '0006_memberimportjob_protected_rows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this role grant is currently in effect. Revoking a role sets this False rather than deleting the row, so revoked grants remain visible as history.'),
        ),
        migrations.AddField(
            model_name='role',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='revoked_by',
            field=models.ForeignKey(blank=True, help_text='The user who revoked this role grant, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'sacco', 'name'), name='unique_active_role_per_user_sacco_name'),
        ),
    ]
