# Generated by Django 6.0.2 on 2026-09-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saccomanagement', '0007_role_soft_revoke'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
