# Generated by Django 6.0.2 on 2026-09-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccomanagement', '0008_remove_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscampaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='smscampaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='DRAFT', max_length=20),
        ),
    ]
