# Generated by Django 6.0.4 on 2026-05-05 12:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
        ('payments', '0002_mpesatransaction'),
        ('saccomembership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuaranteeCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique guarantee capacity identifier.', primary_key=True, serialize=False)),
                ('total_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total savings available for guarantee calculations.', max_digits=12)),
                ('active_guarantees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total active guarantees already committed.', max_digits=12)),
                ('available_capacity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining guarantee capacity.', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time this capacity was last updated.')),
                ('user', models.OneToOneField(help_text='User whose guarantee capacity is tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_capacity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique insurance policy identifier.', primary_key=True, serialize=False)),
                ('policy_number', models.CharField(blank=True, help_text='Optional unique policy number.', max_length=100, null=True, unique=True)),
                ('type', models.CharField(help_text='Insurance product type.', max_length=100)),
                ('coverage_amount', models.DecimalField(decimal_places=2, help_text='Total coverage amount.', max_digits=12)),
                ('premium', models.DecimalField(decimal_places=2, help_text='Insurance premium amount.', max_digits=10)),
                ('start_date', models.DateField(help_text='Policy start date.')),
                ('end_date', models.DateField(help_text='Policy end date.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', help_text='Current insurance policy status.', max_length=20)),
                ('membership', models.ForeignKey(help_text='Membership covered by this insurance policy.', on_delete=django.db.models.deletion.CASCADE, to='saccomembership.membership')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique loan type identifier.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Loan product name.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional loan product description.', null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual loan interest rate percentage.', max_digits=5)),
                ('max_term_months', models.PositiveIntegerField(help_text='Maximum repayment term in months.')),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Minimum loan principal amount.', max_digits=10)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional maximum loan principal amount.', max_digits=10, null=True)),
                ('requires_guarantors', models.BooleanField(default=True, help_text='Whether this loan product requires guarantors.')),
                ('min_guarantors', models.PositiveSmallIntegerField(default=1, help_text='Minimum number of guarantors required.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this loan product is available.')),
                ('sacco', models.ForeignKey(help_text='SACCO that offers this loan type.', on_delete=django.db.models.deletion.CASCADE, to='accounts.sacco')),
            ],
            options={
                'ordering': ['sacco__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique loan identifier.', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Requested loan principal amount.', max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Interest rate applied to this loan.', max_digits=5)),
                ('term_months', models.PositiveIntegerField(help_text='Loan repayment term in months.')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining loan balance.', max_digits=12)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount disbursed to the member.', max_digits=12)),
                ('disbursement_date', models.DateField(blank=True, help_text='Date the loan was disbursed.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GUARANTORS_PENDING', 'Guarantors pending'), ('BOARD_REVIEW', 'Board review'), ('APPROVED', 'Approved'), ('DISBURSEMENT_PENDING', 'Disbursement pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('DEFAULTED', 'Defaulted')], default='PENDING', help_text='Current loan workflow status.', max_length=30)),
                ('application_notes', models.TextField(blank=True, help_text='Optional notes submitted with the loan application.', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason provided when the loan is rejected.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time this loan was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time this loan was last updated.')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Staff user who approved this loan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(help_text='Membership applying for or holding this loan.', on_delete=django.db.models.deletion.PROTECT, to='saccomembership.membership')),
                ('mpesa_transaction', models.ForeignKey(blank=True, help_text='M-Pesa transaction used to disburse this loan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loans', to='payments.mpesatransaction')),
                ('loan_type', models.ForeignKey(blank=True, help_text='Loan product used for this loan.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.loantype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique savings type identifier.', primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('BOSA', 'BOSA'), ('FOSA', 'FOSA'), ('SHARE_CAPITAL', 'Share capital')], help_text='Savings product category.', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Optional savings type description.', max_length=255, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Optional annual interest rate percentage.', max_digits=5, null=True)),
                ('minimum_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum expected contribution amount.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this savings type is available.')),
                ('sacco', models.ForeignKey(help_text='SACCO that owns this savings type.', on_delete=django.db.models.deletion.CASCADE, to='accounts.sacco')),
            ],
            options={
                'ordering': ['sacco__name', 'name'],
                'unique_together': {('name', 'sacco')},
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique guarantor request identifier.', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', help_text='Current guarantor response status.', max_length=20)),
                ('guarantee_amount', models.DecimalField(decimal_places=2, help_text='Amount guaranteed by this user.', max_digits=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the guarantee was requested.')),
                ('responded_at', models.DateTimeField(blank=True, help_text='Date and time the guarantor responded.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional guarantor notes.', null=True)),
                ('guarantor', models.ForeignKey(help_text='User asked to guarantee this loan.', on_delete=django.db.models.deletion.PROTECT, related_name='guarantees', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(help_text='Loan being guaranteed.', on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='services.loan')),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('loan', 'guarantor')},
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique repayment schedule identifier.', primary_key=True, serialize=False)),
                ('instalment_number', models.PositiveIntegerField(help_text='Sequential instalment number for this loan.')),
                ('due_date', models.DateField(db_index=True, help_text='Date this instalment is due.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total instalment amount due.', max_digits=12)),
                ('principal', models.DecimalField(decimal_places=2, help_text='Principal portion of this instalment.', max_digits=12)),
                ('interest', models.DecimalField(decimal_places=2, help_text='Interest portion of this instalment.', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Loan balance after this instalment is paid.', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('PARTIAL', 'Partial')], default='PENDING', help_text='Current instalment payment status.', max_length=20)),
                ('paid_date', models.DateField(blank=True, help_text='Date this instalment was paid.', null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount already paid for this instalment.', max_digits=12, null=True)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Penalty charged for this instalment.', max_digits=12)),
                ('loan', models.ForeignKey(help_text='Loan this instalment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='services.loan')),
            ],
            options={
                'ordering': ['instalment_number'],
                'unique_together': {('loan', 'instalment_number')},
            },
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique savings account identifier.', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current savings balance.', max_digits=12)),
                ('total_contributions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total contributions posted to this account.', max_digits=12)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total withdrawals posted from this account.', max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('CLOSED', 'Closed')], default='ACTIVE', help_text='Current savings account status.', max_length=20)),
                ('dividend_eligible', models.BooleanField(default=True, help_text='Whether this saving qualifies for dividends.')),
                ('last_transaction_date', models.DateField(blank=True, help_text='Date of the latest savings transaction.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this saving was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time this saving was last updated.')),
                ('membership', models.ForeignKey(help_text='Membership that owns this savings account.', on_delete=django.db.models.deletion.PROTECT, to='saccomembership.membership')),
                ('savings_type', models.ForeignKey(blank=True, help_text='Savings product used by this account.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.savingstype')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('membership', 'savings_type')},
            },
        ),
    ]
