# Generated by Codex on 2026-06-27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'reminder_type',
                    models.CharField(
                        choices=[
                            ('THREE_DAY', 'Three day'),
                            ('ONE_DAY', 'One day'),
                            ('OVERDUE', 'Overdue'),
                        ],
                        max_length=20,
                    ),
                ),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('notification_created', models.BooleanField()),
                ('sms_sent', models.BooleanField()),
                (
                    'schedule_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reminder_logs',
                        to='services.repaymentschedule',
                    ),
                ),
            ],
            options={
                'unique_together': {('schedule_item', 'reminder_type')},
            },
        ),
    ]
