# Generated by Django 6.0.2 on 2026-06-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_reminderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Optional notes recorded by SACCO admin during review.', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GUARANTORS_PENDING', 'Guarantors pending'), ('PENDING_APPROVAL', 'Pending approval'), ('UNDER_REVIEW', 'Under review'), ('BOARD_REVIEW', 'Board review'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('DISBURSEMENT_PENDING', 'Disbursement pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('DEFAULTED', 'Defaulted')], default='PENDING', help_text='Current loan workflow status.', max_length=30),
        ),
    ]
