# Generated by Django 6.0.2 on 2026-07-13 05:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_sacco_settings_and_loan_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRBCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique CRB check identifier.', primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Credit score from CRB check (300-850 range).', null=True)),
                ('band', models.CharField(blank=True, choices=[('POOR', 'Poor'), ('FAIR', 'Fair'), ('GOOD', 'Good'), ('VERY_GOOD', 'Very Good'), ('EXCELLENT', 'Excellent')], help_text='Credit band classification.', max_length=20, null=True)),
                ('listed_negative', models.BooleanField(default=False, help_text='Whether the applicant is listed negatively with CRB.')),
                ('provider', models.CharField(default='metropol', help_text='CRB provider used for the check.', max_length=50)),
                ('reference', models.CharField(help_text='Reference number from CRB provider.', max_length=100)),
                ('raw_response', models.JSONField(blank=True, help_text='Raw response from CRB provider for audit purposes.', null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this CRB check was performed.')),
                ('checked_by', models.ForeignKey(blank=True, help_text='User who initiated this CRB check.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crb_checks', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(help_text='Loan this CRB check was performed for.', on_delete=django.db.models.deletion.CASCADE, related_name='crb_checks', to='services.loan')),
            ],
            options={
                'verbose_name': 'CRB Check',
                'verbose_name_plural': 'CRB Checks',
                'ordering': ['-checked_at'],
            },
        ),
    ]
