# Generated by Django 6.0.2 on 2026-07-13 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_saccosettings_liquidity_threshold_percentage'),
        ('services', '0004_crbcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique liquidity alert identifier.', primary_key=True, serialize=False)),
                ('available_reserves', models.DecimalField(decimal_places=2, help_text='Available liquid reserves at time of alert.', max_digits=14)),
                ('pending_disbursements', models.DecimalField(decimal_places=2, help_text='Total pending loan disbursements at time of alert.', max_digits=14)),
                ('utilisation_pct', models.DecimalField(decimal_places=2, help_text='Liquidity utilisation percentage at time of alert.', max_digits=6)),
                ('resolved', models.BooleanField(default=False, help_text='Whether this alert has been resolved.')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Date and time this alert was resolved.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time this alert was created.')),
                ('sacco', models.ForeignKey(help_text='SACCO this alert is for.', on_delete=django.db.models.deletion.CASCADE, related_name='liquidity_alerts', to='accounts.sacco')),
            ],
            options={
                'verbose_name': 'Liquidity Alert',
                'verbose_name_plural': 'Liquidity Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
