# Generated by Django 6.0.2 on 2026-07-15 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_liquidityalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPLFlag',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='Unique NPL flag identifier.',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'threshold_days',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (30, '30 days'),
                            (60, '60 days'),
                            (90, '90 days'),
                        ],
                        help_text=(
                            'Arrears threshold that triggered this flag.'
                        ),
                    ),
                ),
                (
                    'flagged_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text=(
                            'Date and time this NPL flag was created.'
                        ),
                    ),
                ),
                (
                    'resolved',
                    models.BooleanField(
                        default=False,
                        help_text='Whether this NPL flag has been cleared.',
                    ),
                ),
                (
                    'resolved_at',
                    models.DateTimeField(
                        blank=True,
                        help_text=(
                            'Date and time this NPL flag was resolved.'
                        ),
                        null=True,
                    ),
                ),
                (
                    'loan',
                    models.ForeignKey(
                        help_text=(
                            'Loan that crossed this arrears threshold.'
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='npl_flags',
                        to='services.loan',
                    ),
                ),
            ],
            options={
                'ordering': ['-flagged_at'],
                'unique_together': {('loan', 'threshold_days')},
            },
        ),
    ]
