# Generated by Django 6.0.2 on 2026-07-15 08:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_saccosettings_sms_daily_limit'),
        ('saccomembership', '0002_membershipdocument'),
        ('services', '0006_nplflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique dividend declaration identifier.', primary_key=True, serialize=False)),
                ('financial_year', models.CharField(help_text='Financial year (e.g., 2025/2026).', max_length=20)),
                ('declared_rate', models.DecimalField(decimal_places=2, help_text='Annual dividend rate percentage.', max_digits=5)),
                ('period_start', models.DateField(help_text='Start date of dividend calculation period.')),
                ('period_end', models.DateField(help_text='End date of dividend calculation period.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed')], default='DRAFT', help_text='Declaration status.', max_length=20)),
                ('calculated_at', models.DateTimeField(blank=True, help_text='Date and time dividends were calculated.', null=True)),
                ('total_dividend_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total dividend amount calculated.', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time this declaration was created.')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this declaration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dividend_declarations', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(help_text='SACCO this declaration belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='dividend_declarations', to='accounts.sacco')),
                ('savings_type', models.ForeignKey(help_text='Savings type this declaration applies to.', on_delete=django.db.models.deletion.PROTECT, related_name='dividend_declarations', to='services.savingstype')),
            ],
            options={
                'verbose_name': 'Dividend Declaration',
                'verbose_name_plural': 'Dividend Declarations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DividendPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique dividend payout identifier.', primary_key=True, serialize=False)),
                ('average_balance', models.DecimalField(decimal_places=2, help_text='Average monthly balance during calculation period.', max_digits=12)),
                ('dividend_amount', models.DecimalField(decimal_places=2, help_text='Dividend amount calculated.', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CREDITED', 'Credited'), ('PAID', 'Paid')], default='PENDING', help_text='Payout status.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this payout was created.')),
                ('declaration', models.ForeignKey(help_text='Dividend declaration this payout belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='services.dividenddeclaration')),
                ('membership', models.ForeignKey(help_text='Membership receiving this dividend.', on_delete=django.db.models.deletion.CASCADE, related_name='dividend_payouts', to='saccomembership.membership')),
                ('saving', models.ForeignKey(help_text='Saving account this dividend is based on.', on_delete=django.db.models.deletion.CASCADE, related_name='dividend_payouts', to='services.saving')),
            ],
            options={
                'verbose_name': 'Dividend Payout',
                'verbose_name_plural': 'Dividend Payouts',
                'ordering': ['declaration', 'membership'],
                'unique_together': {('declaration', 'saving')},
            },
        ),
    ]
