# Generated by Codex on 2026-08-13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transaction_fee_rate_transaction_gross_amount_and_more'),
        ('services', '0007_dividenddeclaration_dividendpayout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='mpesa_transaction',
            new_name='mpesa_transaction_record',
        ),
        migrations.AlterField(
            model_name='loan',
            name='mpesa_transaction_record',
            field=models.ForeignKey(
                blank=True,
                help_text='M-Pesa transaction used to disburse this loan.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='disbursement_records',
                to='payments.mpesatransaction',
            ),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('INITIATED', 'B2C Initiated'),
                    ('DISBURSED', 'M-Pesa Confirmed'),
                    ('MEMBER_CONFIRMED', 'Member Confirmed'),
                    ('AUTO_CONFIRMED', 'Auto-Confirmed by M-Pesa'),
                    ('DISPUTED', 'Member Disputed'),
                    ('FAILED', 'Disbursement Failed'),
                    ('UNDER_REVIEW', 'Under Admin Review'),
                ],
                default='PENDING',
                help_text='Current fraud-aware disbursement status.',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='loan',
            name='mpesa_conversation_id',
            field=models.CharField(
                blank=True,
                help_text='M-Pesa B2C ConversationID returned at initiation.',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name='loan',
            name='mpesa_transaction_id',
            field=models.CharField(
                blank=True,
                help_text=(
                    'M-Pesa transaction receipt returned on successful '
                    'callback.'
                ),
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_transaction',
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    'Transaction carrying gross, net, and platform fee '
                    'amounts.'
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='loan_disbursements',
                to='payments.transaction',
            ),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='member_confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='member_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='member_disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='DisbursementAuditLog',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'event',
                    models.CharField(
                        choices=[
                            ('LOAN_APPROVED', 'Loan Approved by Admin'),
                            ('B2C_INITIATED', 'M-Pesa B2C API Called'),
                            (
                                'B2C_CALLBACK_RECEIVED',
                                'M-Pesa B2C Callback Received',
                            ),
                            (
                                'MEMBER_NOTIFIED',
                                'Member Confirmation Sent',
                            ),
                            (
                                'MEMBER_CONFIRMED',
                                'Member Confirmed Receipt',
                            ),
                            (
                                'MEMBER_DISPUTED',
                                'Member Reported Non-Receipt',
                            ),
                            (
                                'AUTO_CONFIRMED',
                                'Auto-Confirmed via M-Pesa API',
                            ),
                            (
                                'ESCALATED_TO_SUPERADMIN',
                                'Escalated to Super Admin',
                            ),
                            (
                                'RESOLVED_BY_ADMIN',
                                'Dispute Resolved by Super Admin',
                            ),
                            (
                                'DISBURSEMENT_FAILED',
                                'B2C Payment Failed',
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ('actor_role', models.CharField(max_length=30)),
                ('details', models.JSONField(default=dict)),
                (
                    'ip_address',
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ('mpesa_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'actor',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='disbursement_audit_logs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'loan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='disbursement_audit_logs',
                        to='services.loan',
                    ),
                ),
            ],
            options={
                'db_table': 'disbursement_audit_logs',
                'ordering': ['created_at'],
            },
        ),
    ]
