# Generated by Django 6.0.2 on 2026-09-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_disbursement_fraud_prevention'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disbursement_idempotency_key',
            field=models.UUIDField(blank=True, editable=False, help_text='Server-generated key stamped when a B2C disbursement attempt is claimed under lock. A unique DB constraint backstops the row lock so a second concurrent attempt for this loan can never be recorded, even if application code fails to lock correctly.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursement_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INITIATING', 'Claimed, Calling M-Pesa'), ('INITIATED', 'B2C Initiated'), ('PENDING_CONFIRMATION', 'M-Pesa Response Unknown (Timed Out)'), ('DISBURSED', 'M-Pesa Confirmed'), ('MEMBER_CONFIRMED', 'Member Confirmed'), ('AUTO_CONFIRMED', 'Auto-Confirmed by M-Pesa'), ('DISPUTED', 'Member Disputed'), ('FAILED', 'Disbursement Failed'), ('UNDER_REVIEW', 'Under Admin Review')], default='PENDING', help_text='Current fraud-aware disbursement status.', max_length=30),
        ),
    ]
