# Generated by Django 6.0.2 on 2026-09-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_dividendpayout_divpayout_decl_status_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursementauditlog',
            name='event',
            field=models.CharField(
                choices=[
                    ('LOAN_APPROVED', 'Loan Approved by Admin'),
                    ('B2C_INITIATED', 'M-Pesa B2C API Called'),
                    (
                        'B2C_CALLBACK_RECEIVED',
                        'M-Pesa B2C Callback Received',
                    ),
                    ('MEMBER_NOTIFIED', 'Member Confirmation Sent'),
                    ('MEMBER_CONFIRMED', 'Member Confirmed Receipt'),
                    ('MEMBER_DISPUTED', 'Member Reported Non-Receipt'),
                    (
                        'AUTO_CONFIRMED',
                        'Auto-Confirmed via M-Pesa API',
                    ),
                    (
                        'ESCALATED_TO_SUPERADMIN',
                        'Escalated to Super Admin',
                    ),
                    (
                        'RESOLVED_BY_ADMIN',
                        'Dispute Resolved by Super Admin',
                    ),
                    ('DISBURSEMENT_FAILED', 'B2C Payment Failed'),
                    (
                        'B2C_ALTERNATE_NUMBER_AUTHORIZED',
                        'Disbursement Authorized to Alternate Number',
                    ),
                ],
                max_length=40,
            ),
        ),
    ]
