# Generated by Django 6.0.2 on 2026-09-13 20:35

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_alter_disbursementauditlog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=services.models.default_guarantor_response_deadline, help_text='Deadline for the guarantor to respond before expire_stale_internal_guarantors_task marks this EXPIRED. Null on rows created before this field existed - those are never swept.', null=True),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', help_text='Current guarantor response status.', max_length=20),
        ),
    ]
