# Generated by Django 5.1.1 on 2026-06-24 11:26

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique callback identifier.', primary_key=True, serialize=False)),
                ('raw_payload', models.JSONField(help_text='Raw provider callback payload.')),
                ('processed', models.BooleanField(default=False, help_text='Whether this callback has been processed.')),
                ('processing_error', models.TextField(blank=True, help_text='Processing error message, if processing failed.', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this callback was received.')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Date and time this callback was processed.', null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(help_text='Checkout request identifier already processed.', max_length=100, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this checkout request was processed.')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique M-Pesa transaction identifier.', primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Phone number used for the M-Pesa transaction.', max_length=13)),
                ('merchant_request_id', models.CharField(blank=True, help_text='M-Pesa merchant request identifier.', max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, help_text='M-Pesa checkout request identifier.', max_length=100, null=True, unique=True)),
                ('conversation_id', models.CharField(blank=True, db_index=True, help_text='M-Pesa conversation identifier.', max_length=100, null=True)),
                ('originator_conversation_id', models.CharField(blank=True, help_text='M-Pesa originator conversation identifier.', max_length=100, null=True)),
                ('transaction_type', models.CharField(choices=[('STK_PUSH', 'STK Push'), ('B2C', 'B2C')], default='STK_PUSH', help_text='M-Pesa transaction flow type.', max_length=20)),
                ('result_code', models.CharField(blank=True, help_text='Provider result code.', max_length=10, null=True)),
                ('result_description', models.TextField(blank=True, help_text='Provider result description.', null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='M-Pesa receipt number.', max_length=50, null=True)),
                ('callback_received', models.BooleanField(default=False, help_text='Whether an M-Pesa callback has been received.')),
                ('related_instalment_number', models.PositiveIntegerField(blank=True, help_text='Repayment instalment number affected by this transaction.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this M-Pesa record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time this M-Pesa record was last updated.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique payment provider identifier.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Payment provider display name.', max_length=100, unique=True)),
                ('provider_type', models.CharField(choices=[('MPESA', 'M-Pesa'), ('AIRTEL', 'Airtel'), ('BANK', 'Bank'), ('INTERNAL', 'Internal')], help_text='Type of payment provider.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment provider is active.')),
                ('config', models.JSONField(default=dict, help_text='Provider configuration such as endpoints. Do not store secrets.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this provider was created.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique platform fee identifier.', primary_key=True, serialize=False)),
                ('fee_type', models.CharField(choices=[('TRANSACTION_PCT', 'Transaction percentage'), ('MONTHLY_SAAS', 'Monthly SaaS')], help_text='Type of platform fee.', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Platform fee amount.', max_digits=10)),
                ('invoice_number', models.CharField(blank=True, help_text='Optional invoice number for this fee.', max_length=50, null=True)),
                ('processed', models.BooleanField(default=False, help_text='Whether this platform fee has been processed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this fee was created.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique transaction identifier.', primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, help_text='Internal SaccoSphere transaction reference.', max_length=100, unique=True)),
                ('external_reference', models.CharField(blank=True, db_index=True, help_text='External provider transaction reference.', max_length=100, null=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('LOAN_REPAYMENT', 'Loan repayment'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('FEE', 'Fee')], default='DEPOSIT', help_text='Business purpose of this transaction.', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount.', max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee charged for this transaction.', max_digits=10)),
                ('currency', models.CharField(default='KES', help_text='ISO currency code.', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', help_text='Current transaction status.', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Optional transaction description.', max_length=255, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional non-sensitive transaction metadata.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time this transaction was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time this transaction was last updated.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
