# Generated by Django 5.1.1 on 2026-06-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='related_loan',
            field=models.ForeignKey(blank=True, help_text='Loan affected by this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.loan'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='related_saving',
            field=models.ForeignKey(blank=True, help_text='Saving affected by this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.saving'),
        ),
        migrations.AddField(
            model_name='callback',
            name='provider',
            field=models.ForeignKey(help_text='Provider that sent this callback.', on_delete=django.db.models.deletion.PROTECT, to='payments.paymentprovider'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Payment provider used for this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentprovider'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(help_text='User who owns this transaction.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platformfee',
            name='transaction',
            field=models.ForeignKey(help_text='Transaction this platform fee belongs to.', on_delete=django.db.models.deletion.PROTECT, to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='transaction',
            field=models.OneToOneField(blank=True, help_text='Main transaction linked to this M-Pesa record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='callback',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Transaction linked to this callback, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'created_at'], name='payments_tr_user_id_4ab1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='payments_tr_status_e3597b_idx'),
        ),
    ]
