# Generated by Django 6.0.4 on 2026-05-05 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique M-Pesa transaction identifier.', primary_key=True, serialize=False)),
                ('checkout_request_id', models.CharField(blank=True, help_text='M-Pesa checkout request identifier.', max_length=100, null=True, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='M-Pesa receipt number.', max_length=100, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number used for the M-Pesa transaction.', max_length=13, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='M-Pesa transaction amount.', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed')], default='PENDING', help_text='Current M-Pesa transaction status.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this M-Pesa transaction was created.')),
                ('user', models.ForeignKey(blank=True, help_text='User linked to this M-Pesa transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
