# Generated by Django 6.0.4 on 2026-05-05 13:28

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_mpesatransaction'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(help_text='Checkout request identifier already processed.', max_length=100, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this checkout request was processed.')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique payment provider identifier.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Payment provider display name.', max_length=100, unique=True)),
                ('provider_type', models.CharField(choices=[('MPESA', 'M-Pesa'), ('AIRTEL', 'Airtel'), ('BANK', 'Bank'), ('INTERNAL', 'Internal')], help_text='Type of payment provider.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment provider is active.')),
                ('config', models.JSONField(default=dict, help_text='Provider configuration such as endpoints. Do not store secrets.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this provider was created.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique platform fee identifier.', primary_key=True, serialize=False)),
                ('fee_type', models.CharField(choices=[('TRANSACTION_PCT', 'Transaction percentage'), ('MONTHLY_SAAS', 'Monthly SaaS')], help_text='Type of platform fee.', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Platform fee amount.', max_digits=10)),
                ('invoice_number', models.CharField(blank=True, help_text='Optional invoice number for this fee.', max_length=50, null=True)),
                ('processed', models.BooleanField(default=False, help_text='Whether this platform fee has been processed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this fee was created.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='callback_received',
            field=models.BooleanField(default=False, help_text='Whether an M-Pesa callback has been received.'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='conversation_id',
            field=models.CharField(blank=True, db_index=True, help_text='M-Pesa conversation identifier.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='merchant_request_id',
            field=models.CharField(blank=True, help_text='M-Pesa merchant request identifier.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='originator_conversation_id',
            field=models.CharField(blank=True, help_text='M-Pesa originator conversation identifier.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='related_instalment_number',
            field=models.PositiveIntegerField(blank=True, help_text='Repayment instalment number affected by this transaction.', null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='related_loan',
            field=models.ForeignKey(blank=True, help_text='Loan affected by this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.loan'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='related_saving',
            field=models.ForeignKey(blank=True, help_text='Saving affected by this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.saving'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='result_code',
            field=models.CharField(blank=True, help_text='Provider result code.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='result_description',
            field=models.TextField(blank=True, help_text='Provider result description.', null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='transaction',
            field=models.OneToOneField(blank=True, help_text='Main transaction linked to this M-Pesa record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='transaction_type',
            field=models.CharField(choices=[('STK_PUSH', 'STK Push'), ('B2C', 'B2C')], default='STK_PUSH', help_text='M-Pesa transaction flow type.', max_length=20),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this M-Pesa record was last updated.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='KES', help_text='ISO currency code.', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, help_text='Optional transaction description.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, help_text='External provider transaction reference.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee charged for this transaction.', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Additional non-sensitive transaction metadata.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('LOAN_REPAYMENT', 'Loan repayment'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('FEE', 'Fee')], default='DEPOSIT', help_text='Business purpose of this transaction.', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this transaction was last updated.'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, db_index=True, help_text='M-Pesa checkout request identifier.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time this M-Pesa record was created.'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, help_text='M-Pesa receipt number.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone_number',
            field=models.CharField(help_text='Phone number used for the M-Pesa transaction.', max_length=13),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Transaction amount.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time this transaction was created.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique transaction identifier.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(db_index=True, help_text='Internal SaccoSphere transaction reference.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', help_text='Current transaction status.', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(help_text='User who owns this transaction.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique callback identifier.', primary_key=True, serialize=False)),
                ('raw_payload', models.JSONField(help_text='Raw provider callback payload.')),
                ('processed', models.BooleanField(default=False, help_text='Whether this callback has been processed.')),
                ('processing_error', models.TextField(blank=True, help_text='Processing error message, if processing failed.', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this callback was received.')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Date and time this callback was processed.', null=True)),
                ('transaction', models.ForeignKey(blank=True, help_text='Transaction linked to this callback, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction')),
                ('provider', models.ForeignKey(help_text='Provider that sent this callback.', on_delete=django.db.models.deletion.PROTECT, to='payments.paymentprovider')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Payment provider used for this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentprovider'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'created_at'], name='payments_tr_user_id_4ab1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='payments_tr_status_e3597b_idx'),
        ),
        migrations.AddField(
            model_name='platformfee',
            name='transaction',
            field=models.ForeignKey(help_text='Transaction this platform fee belongs to.', on_delete=django.db.models.deletion.PROTECT, to='payments.transaction'),
        ),
    ]
