# Generated by Django 5.2.16 on 2026-07-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformfee',
            name='processed',
        ),
    ]
