# Generated by Django 6.0.2 on 2026-08-13 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_kycverification_iprs_attempted_at_and_more'),
        ('payments', '0004_transaction_status_sent_amount_mismatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee_rate',
            field=models.DecimalField(decimal_places=6, help_text='Percentage fee rate applied, null for tiered flat fees.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, help_text='Gross amount paid or approved before platform fee.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, help_text='Platform fee charged or retained for this transaction.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sacco',
            field=models.ForeignKey(blank=True, help_text='SACCO responsible for this transaction.', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.sacco'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Net transaction amount.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('repayment', 'Loan Repayment'), ('disbursement', 'Loan Disbursement'), ('withdrawal', 'Savings Withdrawal')], default='deposit', help_text='Business purpose of this transaction.', max_length=20),
        ),
    ]
