# Generated by Codex on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transaction_fee_rate_transaction_gross_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('PROCESSING', 'Processing'),
                    ('SENT', 'Sent'),
                    ('INITIATION_FAILED', 'Initiation failed'),
                    ('COMPLETED', 'Completed'),
                    ('FAILED', 'Failed'),
                    ('AMOUNT_MISMATCH', 'Amount mismatch'),
                    ('REVERSED', 'Reversed'),
                ],
                default='PENDING',
                help_text='Current transaction status.',
                max_length=20,
            ),
        ),
    ]
