# Generated by Django 6.0.2 on 2026-09-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('PROCESSING', 'Processing'),
                    ('SENT', 'Sent'),
                    ('INITIATION_FAILED', 'Initiation failed'),
                    (
                        'PENDING_CONFIRMATION',
                        'M-Pesa Response Unknown (Timed Out)',
                    ),
                    ('UNDER_REVIEW', 'Under Admin Review'),
                    ('COMPLETED', 'Completed'),
                    ('FAILED', 'Failed'),
                    ('AMOUNT_MISMATCH', 'Amount mismatch'),
                    ('REVERSED', 'Reversed'),
                ],
                default='PENDING',
                help_text='Current transaction status.',
                max_length=20,
            ),
        ),
    ]
