# Generated by Django 5.1.1 on 2026-06-24 11:26

import accounts.models
import accounts.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique user identifier.', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, help_text='Optional legacy username. Email is used for login.', max_length=150, null=True)),
                ('email', models.EmailField(db_index=True, help_text='User email address. Used as the login identifier.', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, help_text='Phone number in E.164 format, for example 254712345678.', max_length=13, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Optional user profile picture.', null=True, upload_to='profiles/')),
                ('date_of_birth', models.DateField(blank=True, help_text='Optional user date of birth.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['first_name', 'last_name', 'email'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique KYC verification identifier.', primary_key=True, serialize=False)),
                ('id_number', models.CharField(blank=True, help_text='Kenya National ID number.', max_length=20, null=True)),
                ('id_front', models.ImageField(blank=True, help_text='Front image of the national ID.', null=True, storage=accounts.storage.KYCDocumentStorage(), upload_to='kyc/front/')),
                ('id_back', models.ImageField(blank=True, help_text='Back image of the national ID.', null=True, storage=accounts.storage.KYCDocumentStorage(), upload_to='kyc/back/')),
                ('passport', models.ImageField(blank=True, help_text='Optional passport image.', null=True, storage=accounts.storage.KYCDocumentStorage(), upload_to='kyc/passport/')),
                ('huduma', models.ImageField(blank=True, help_text='Optional Huduma card image.', null=True, storage=accounts.storage.KYCDocumentStorage(), upload_to='kyc/huduma/')),
                ('huduma_namba', models.CharField(blank=True, help_text='Optional Huduma Namba.', max_length=20, null=True)),
                ('iprs_verified', models.BooleanField(default=False, help_text='Whether identity was verified through IPRS.')),
                ('iprs_reference', models.CharField(blank=True, help_text='IPRS verification reference number.', max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_STARTED', 'Not started')], default='NOT_STARTED', help_text='Current KYC review status.', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason provided when KYC is rejected.', null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Date and time the KYC was approved.', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Date and time the user submitted KYC documents.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this KYC record was created.')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff user who reviewed this KYC record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User whose identity is being verified.', on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique OTP token identifier.', primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Phone number receiving the OTP.', max_length=13)),
                ('code', models.CharField(help_text='Six-digit OTP code stored as a string.', max_length=6)),
                ('purpose', models.CharField(choices=[('PHONE_VERIFY', 'Phone verification'), ('PASSWORD_RESET', 'Password reset'), ('LOGIN', 'Login')], default='PHONE_VERIFY', help_text='Reason this OTP was created.', max_length=20)),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Whether this OTP has already been used.')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of failed verification attempts.')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Date and time this OTP expires.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time this OTP was created.')),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this OTP token. Null for registration OTPs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique SACCO identifier.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Official SACCO name.', max_length=200, unique=True)),
                ('registration_number', models.CharField(blank=True, help_text='Official cooperative registration number.', max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short public description of the SACCO.', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Optional SACCO logo.', null=True, upload_to='sacco_logos/')),
                ('sector', models.CharField(choices=[('EDUCATION', 'Education'), ('HEALTHCARE', 'Healthcare'), ('AGRICULTURE', 'Agriculture'), ('TRANSPORT', 'Transport'), ('GOVERNMENT', 'Government'), ('TECHNOLOGY', 'Technology'), ('FINANCE', 'Finance'), ('RETAIL', 'Retail'), ('OTHER', 'Other')], help_text='Main sector served by the SACCO.', max_length=50)),
                ('county', models.CharField(help_text='Kenya county where the SACCO is based.', max_length=50)),
                ('membership_type', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('STAFF_ONLY', 'Staff only')], default='OPEN', help_text='Controls who can join this SACCO.', max_length=20)),
                ('is_publicly_listed', models.BooleanField(default=True, help_text='Whether the SACCO is visible in public listings.')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether SaccoSphere has verified this SACCO.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this SACCO can currently operate on the platform.')),
                ('default_interest_rate', models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Default annual loan interest rate percentage.', max_digits=5)),
                ('loan_multiplier', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Maximum loan multiplier based on member savings.', max_digits=4)),
                ('min_loan_months', models.PositiveIntegerField(default=3, help_text='Minimum membership duration before loan eligibility.')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Joining fee in KES.', max_digits=10)),
                ('website', models.URLField(blank=True, help_text='Optional SACCO website URL.', null=True)),
                ('email', models.EmailField(blank=True, help_text='Optional SACCO contact email.', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Optional SACCO phone number in E.164 format.', max_length=13, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time this SACCO was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time this SACCO was last updated.')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sector', 'county'], name='accounts_sa_sector_556eda_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique user consent identifier.', primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('TERMS', 'Terms'), ('PRIVACY', 'Privacy'), ('DATA_PROCESSING', 'Data processing'), ('MARKETING', 'Marketing')], help_text='Type of consent being recorded.', max_length=30)),
                ('version', models.CharField(help_text='Policy version, for example v1.2.', max_length=20)),
                ('consented', models.BooleanField(help_text='Whether the user accepted this consent.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address used when consent was recorded.', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser or client user agent.', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date and time the consent was recorded.')),
                ('user', models.ForeignKey(help_text='User who gave or denied consent.', on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
