# Generated by Django 6.0.2 on 2026-06-27 12:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaccoSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12)),
                ('loan_multiplier', models.PositiveSmallIntegerField(default=3)),
                ('requires_guarantor', models.BooleanField(default=True)),
                ('guarantor_type_allowed', models.CharField(choices=[('MEMBER_ONLY', 'Member only'), ('EXTERNAL_ONLY', 'External only'), ('BOTH', 'Both')], default='BOTH', max_length=20)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monthly_contribution_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sacco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.sacco')),
            ],
            options={
                'ordering': ['sacco__name'],
            },
        ),
    ]
