# Generated by Django 5.0.6 on 2026-05-07 05:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacco',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Joining fee in KES.', max_digits=10),
        ),
    ]
