# Generated by Django 6.0.2 on 2026-07-13 06:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sacco_settings_and_loan_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='saccosettings',
            name='liquidity_threshold_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Liquidity utilisation percentage at which a warning fires.', max_digits=5),
        ),
    ]
