# Generated by Django 6.0.2 on 2026-07-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_saccosettings_liquidity_threshold_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='saccosettings',
            name='sms_daily_limit',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
