# Generated by Codex on 2026-05-11

import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sacco_registration_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='id_back',
            field=models.ImageField(
                blank=True,
                help_text='Back image of the national ID.',
                null=True,
                storage=accounts.storage.KYCDocumentStorage(),
                upload_to='kyc/back/',
            ),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='id_front',
            field=models.ImageField(
                blank=True,
                help_text='Front image of the national ID.',
                null=True,
                storage=accounts.storage.KYCDocumentStorage(),
                upload_to='kyc/front/',
            ),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='passport',
            field=models.ImageField(
                blank=True,
                help_text='Optional passport image.',
                null=True,
                storage=accounts.storage.KYCDocumentStorage(),
                upload_to='kyc/passport/',
            ),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='huduma',
            field=models.ImageField(
                blank=True,
                help_text='Optional Huduma card image.',
                null=True,
                storage=accounts.storage.KYCDocumentStorage(),
                upload_to='kyc/huduma/',
            ),
        ),
    ]
