# Generated by Django 6.0.2 on 2026-07-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_saccosettings_sms_daily_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saccosettings',
            name='sms_daily_limit',
            field=models.PositiveIntegerField(default=1000, help_text='Daily SMS send limit to control costs.'),
        ),
    ]
