# Generated by Django 6.0.2 on 2026-07-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_saccosettings_sms_daily_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='iprs_attempted_at',
            field=models.DateTimeField(blank=True, help_text='Date and time IPRS verification was last attempted.', null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='iprs_error',
            field=models.CharField(blank=True, help_text='Short IPRS error or mismatch reason.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='manual_verification_reason',
            field=models.CharField(blank=True, help_text='Admin reason for approving a manually verified KYC.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IPRS_MISMATCH', 'IPRS mismatch'), ('PENDING_MANUAL', 'Pending manual review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_STARTED', 'Not started')], default='NOT_STARTED', help_text='Current KYC review status.', max_length=20),
        ),
    ]
