# Generated by Django 5.0.6 on 2026-06-15 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('accounts', '0006_create_otptoken'),
]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this OTP token. Null for registration OTPs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
