# Generated by Django 6.0.2 on 2026-08-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_kycverification_iprs_attempted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacco',
            name='is_billing_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sacco',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sacco',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
    ]
