# Generated by Django 6.0.6 on 2026-08-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sacco_is_billing_suspended_sacco_suspended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='channel',
            field=models.CharField(choices=[('PHONE', 'Phone (SMS)'), ('EMAIL', 'Email')], default='PHONE', help_text='Delivery channel used to send the OTP (SMS or email).', max_length=10),
        ),
    ]
