# Generated by Django 6.0.2 on 2026-08-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otptoken_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, help_text='Google account identifier (sub claim) for OAuth sign-in.', max_length=255, null=True, unique=True),
        ),
    ]
