# Generated by Django 6.0.2 on 2026-08-25 11:15

import accounts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_otptoken_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaccoPaymentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique payment config identifier.', primary_key=True, serialize=False)),
                ('shortcode_type', models.CharField(choices=[('PAYBILL', 'Paybill Number'), ('TILL_NUMBER', 'Till Number')], default='PAYBILL', help_text='Type of M-Pesa shortcode (Paybill or Till Number).', max_length=20)),
                ('shortcode', models.CharField(help_text='M-Pesa shortcode number (Paybill or Till Number).', max_length=10)),
                ('stk_passkey', accounts.models.EncryptedCharField(blank=True, help_text='STK push passkey for this shortcode (encrypted at rest).', max_length=255, null=True)),
                ('daraja_consumer_key', models.CharField(blank=True, help_text='Daraja consumer key (nullable if using platform aggregator).', max_length=255, null=True)),
                ('daraja_consumer_secret', accounts.models.EncryptedCharField(blank=True, help_text='Daraja consumer secret (encrypted at rest, nullable if using platform aggregator).', max_length=255, null=True)),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('LIVE', 'Live')], default='SANDBOX', help_text='Daraja environment (Sandbox or Live).', max_length=20)),
                ('b2c_initiator_name', models.CharField(blank=True, help_text='B2C initiator name for disbursements (nullable if SACCO does not disburse).', max_length=100, null=True)),
                ('b2c_security_credential', accounts.models.EncryptedCharField(blank=True, help_text='B2C encrypted security credential (encrypted at rest, nullable if SACCO does not disburse).', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment configuration is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sacco', models.OneToOneField(help_text='The SACCO this payment configuration belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='accounts.sacco')),
            ],
            options={
                'verbose_name': 'SACCO Payment Configuration',
                'verbose_name_plural': 'SACCO Payment Configurations',
                'ordering': ['sacco__name'],
            },
        ),
    ]
