# Generated by Django 6.0.2 on 2026-08-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_sacco_payment_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacco',
            name='payment_ready',
            field=models.BooleanField(default=False, help_text='Whether this SACCO has completed M-Pesa Daraja onboarding and can process payments.'),
        ),
    ]
