# Generated by Django 6.0.2 on 2026-08-26 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_payment_ready_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the phone number was verified via OTP.', null=True),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique password reset token identifier.', primary_key=True, serialize=False)),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Whether this reset token has been used to change the password.')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Token expiration timestamp.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Token creation timestamp.')),
                ('otp_token', models.OneToOneField(help_text='The OTP token that was verified to generate this reset token.', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_token', to='accounts.otptoken')),
                ('user', models.ForeignKey(help_text='User requesting password reset.', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used'], name='accounts_pa_user_id_023f8d_idx'), models.Index(fields=['expires_at'], name='accounts_pa_expires_01b447_idx')],
            },
        ),
    ]
