# Generated by Django 6.0.2 on 2026-08-26 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_phone_verified_at_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataErasureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique data erasure request identifier.', primary_key=True, serialize=False)),
                ('user_email_anonymized', models.CharField(blank=True, help_text='Anonymized email reference for audit trail after user deletion.', max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', help_text='Current status of the erasure request.', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the erasure request was submitted.')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when the request was reviewed.', null=True)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Notes from the reviewer explaining the decision.', null=True)),
                ('reason', models.TextField(blank=True, help_text='User-provided reason for the erasure request.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when anonymization was completed.', null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff user who reviewed the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_erasure_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User requesting erasure. Null after anonymization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasure_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_da_user_id_470da3_idx'), models.Index(fields=['status', 'requested_at'], name='accounts_da_status_768d73_idx')],
            },
        ),
    ]
