# Generated by Django 6.0.2 on 2026-08-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_dataerasurerequest'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='otptoken',
            constraint=models.UniqueConstraint(condition=models.Q(('is_used', False)), fields=('phone_number', 'purpose'), name='unique_active_otp_per_phone_purpose', violation_error_message='An active OTP token already exists for this phone number and purpose. Please wait for the existing token to expire or be used before requesting a new one.'),
        ),
    ]
