# Generated by Django 6.0.2 on 2026-08-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_kycverification_normalized_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataerasurerequest',
            name='hold_reason',
            field=models.CharField(blank=True, choices=[('REGULATORY_INVESTIGATION', 'Regulatory Investigation'), ('DISPUTE_IN_PROGRESS', 'Dispute In Progress'), ('LEGAL_HOLD', 'Legal Hold'), ('AUDIT_IN_PROGRESS', 'Audit In Progress')], help_text='Reason for hold if status is ON_HOLD.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dataerasurerequest',
            name='hold_until',
            field=models.DateTimeField(blank=True, help_text='Date until which the hold applies.', null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='retention_until',
            field=models.DateTimeField(blank=True, help_text='Date until which KYC documents must be retained.', null=True),
        ),
        migrations.AlterField(
            model_name='dataerasurerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], db_index=True, default='PENDING', help_text='Current status of the erasure request.', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IPRS_MISMATCH', 'IPRS mismatch'), ('PENDING_MANUAL', 'Pending manual review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_STARTED', 'Not started'), ('IPRS_REJECTED', 'Rejected by IPRS'), ('IPRS_UNAVAILABLE', 'IPRS unavailable')], default='NOT_STARTED', help_text='Current KYC review status.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='dataerasurerequest',
            index=models.Index(fields=['status', 'hold_until'], name='accounts_da_status_299948_idx'),
        ),
    ]
