# Generated by Django 6.0.2 on 2026-08-28 13:57
#
# This migration adds a unique constraint on (user, consent_type, version) to
# prevent duplicate consent records, adds a composite index for efficient
# consent status lookups, and updates the ip_address help_text.
#
# Duplicate check: No duplicate (user, consent_type, version) rows found in
# UserConsent prior to adding the unique constraint. The constraint can be
# applied cleanly without data migration.
#
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_dataerasurerequest_hold_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address used when consent was recorded. Nullable at model level for admin/migrated records, but API layer should require this for public consent endpoints.', null=True),
        ),
        migrations.AddIndex(
            model_name='userconsent',
            index=models.Index(fields=['user', 'consent_type', '-timestamp'], name='user_consent_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='userconsent',
            constraint=models.UniqueConstraint(fields=('user', 'consent_type', 'version'), name='unique_user_consent_per_version', violation_error_message='A consent record for this user, consent type, and version already exists.'),
        ),
    ]
