# Generated by Django 6.0.2 on 2026-08-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_userconsent_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsent',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, help_text='Date and time consent was withdrawn. Null for active consents.', null=True),
        ),
    ]
