# Generated by Django 6.0.6 on 2026-09-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userconsent_withdrawn_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsent',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Date and time this consent expires, if this consent_type has a configured expiry duration (see settings.CONSENT_EXPIRY_DURATIONS). Null means this consent does not expire.', null=True),
        ),
    ]
