# Generated by Django 6.0.6 on 2026-09-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_userconsent_expires_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userconsent',
            name='unique_user_consent_per_version',
        ),
        migrations.AddConstraint(
            model_name='userconsent',
            constraint=models.UniqueConstraint(condition=models.Q(('withdrawn_at__isnull', True)), fields=('user', 'consent_type', 'version'), name='unique_active_user_consent_per_version', violation_error_message='An active consent record for this user, consent type, and version already exists.'),
        ),
    ]
