# Generated by Django 6.0.2 on 2026-09-07 14:43

from django.db import migrations, models


def backfill_next_member_number_seq(apps, schema_editor):
    """
    Seed each existing SACCO's counter from its current APPROVED member
    count, so member numbers generated going forward don't collide in
    spirit with the size of the membership that already exists. Existing
    members are not retroactively assigned a member_number by this
    migration - only the counter baseline is set.
    """
    Sacco = apps.get_model('accounts', 'Sacco')
    Membership = apps.get_model('saccomembership', 'Membership')

    for sacco in Sacco.objects.all():
        approved_count = Membership.objects.filter(
            sacco=sacco,
            status='APPROVED',
        ).count()
        if approved_count:
            sacco.next_member_number_seq = approved_count
            sacco.save(update_fields=['next_member_number_seq'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_userconsent_unique_active_constraint'),
        ('saccomembership', '0002_membershipdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacco',
            name='next_member_number_seq',
            field=models.PositiveIntegerField(default=0, help_text='Internal counter for generating the next member_number for this SACCO. Not user-editable; incremented atomically by saccomembership.services.generate_member_number.'),
        ),
        migrations.RunPython(
            backfill_next_member_number_seq,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
