# Generated by Django 6.0.2 on 2026-09-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_sacco_next_member_number_seq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saccopaymentconfig',
            options={'ordering': ['sacco__name'], 'permissions': [('manage_payment_secrets', 'Can view and change M-Pesa/Daraja payment secrets')], 'verbose_name': 'SACCO Payment Configuration', 'verbose_name_plural': 'SACCO Payment Configurations'},
        ),
    ]
