# Generated by Django 6.0.2 on 2026-09-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_saccopaymentconfig_manage_payment_secrets_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saccosettings',
            name='requires_guarantor',
        ),
    ]
