# Generated by Django 6.0.2 on 2026-09-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_saccosettings_dividend_calculation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='saccosettings',
            name='sms_sent_today_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saccosettings',
            name='sms_sent_today_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
