# Generated by Django 6.0.2 on 2026-09-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_sacco_settings_sms_daily_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacco',
            name='billing_exempt',
            field=models.BooleanField(default=False, help_text='When true, billing.tasks.suspend_overdue_saccos skips this SACCO regardless of overdue invoices (e.g. a pilot deal or a billing dispute in progress). Set/cleared by a super admin via SaccoBillingExemptionView, never automatically.'),
        ),
        migrations.AddField(
            model_name='sacco',
            name='billing_exempt_reason',
            field=models.TextField(blank=True),
        ),
    ]
