# Generated by Django 5.1.1 on 2026-06-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('LOAN', 'Loan'), ('PAYMENT', 'Payment'), ('ALERT', 'Alert'), ('GUARANTOR', 'Guarantor'), ('DIVIDEND', 'Dividend'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
    ]
