# Generated by Django 6.0.2 on 2026-07-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('LOAN', 'Loan'), ('PAYMENT', 'Payment'), ('ALERT', 'Alert'), ('LIQUIDITY_WARNING', 'Liquidity warning'), ('GUARANTOR', 'Guarantor'), ('DIVIDEND', 'Dividend'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
    ]
