# Generated by Django 6.0.2 on 2026-09-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saccomembership', '0002_membershipdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saccoapplication',
            name='additional_docs',
        ),
    ]
