web: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi:application
worker: celery -A config.celery worker -Q payments,notifications,reports,default -l info
beat: celery -A config.celery beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
