# Generated by Django 5.1.1 on 2026-06-27 07:04

import django.db.models.deletion
import guarantor.models
import guarantor.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userdevice'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('employment_status', models.CharField(choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self employed'), ('BUSINESS_OWNER', 'Business owner'), ('RETIRED', 'Retired'), ('OTHER', 'Other')], max_length=20)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guarantee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='external_guarantors/id_front/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='external_guarantors/id_back/')),
                ('status', models.CharField(choices=[('PENDING_SMS', 'Pending SMS'), ('SMS_SENT', 'SMS sent'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('UNDER_ADMIN_REVIEW', 'Under admin review'), ('APPROVED_BY_ADMIN', 'Approved by admin'), ('REJECTED_BY_ADMIN', 'Rejected by admin')], default='PENDING_SMS', max_length=30)),
                ('response_token', models.CharField(default=guarantor.utils.generate_response_token, max_length=64, unique=True)),
                ('response_token_expires_at', models.DateTimeField(default=guarantor.models.default_response_token_expires_at)),
                ('guarantor_response', models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], max_length=20, null=True)),
                ('guarantor_response_notes', models.TextField(blank=True, null=True)),
                ('guarantor_responded_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_guarantors', to='services.loan')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_guarantor_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_guarantor_reviews', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sacco')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
