# Generated by Django 5.2.6 on 2025-09-05 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('management', models.CharField(choices=[('verified', 'Verified'), ('updated', 'Updated'), ('removed', 'Removed')], max_length=20)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saccomanagement', to='accounts.sacco')),
            ],
        ),
    ]
